In [1]:
# 2-10

import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [2]:
x[0]

1

In [3]:
x[2] = 100   # 3番目の要素を100に変更する
x

array([  1,   2, 100])

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y            # 要素ごとの足し算

array([5, 7, 9])

In [5]:
x - y            # 要素ごとの引き算

array([-3, -3, -3])

In [6]:
x*y              # 要素ごとの掛け算

array([ 4, 10, 18])

In [7]:
x/y              # 要素ごとの割り算

array([0.25, 0.4 , 0.5 ])

In [11]:
x = np.array([1, 2, 3, 4, 5], dtype = float)   # dtypeで明示的に型を指定

In [12]:
x + 10

array([11., 12., 13., 14., 15.])

In [13]:
x - 1

array([0., 1., 2., 3., 4.])

In [14]:
x*10

array([10., 20., 30., 40., 50.])

In [15]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [16]:
x//2

array([0., 1., 1., 2., 2.])

In [17]:
x%2

array([1., 0., 1., 0., 1.])

In [18]:
# 累乗、平方根

x = np.array([1, 2, 3, 4, 5], dtype = float)
np.power(x, 2)

array([ 1.,  4.,  9., 16., 25.])

In [19]:
x**2

array([ 1.,  4.,  9., 16., 25.])

In [20]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [21]:
# ベクトル同士の演算

vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

In [22]:
vec1 + vec2                # ベクトル同士の足し算

array([50, 70, 90])

In [23]:
vec1 - vec2                # ベクトル同士の引き算

array([-30, -30, -30])

In [24]:
vec1/vec2                  # ベクトル同士の割り算

array([0.25, 0.4 , 0.5 ])

In [25]:
# アダマール積

vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

In [26]:
vec1*vec2       # アダマール積を求める

array([ 400, 1000, 1800])

In [27]:
# 内積

vec1 = np.array([2, 3])
vec2 = np.array([4, 5])
np.dot(vec1, vec2)          # vec1とvec2の内積を求める

23

In [28]:
vec3 = np.array([4, 5, -6])
vec4 = np.array([-2, 3, -1])
np.dot(vec3, vec4)          # vec3とvec4の内積を求める

13

In [29]:
# 行列

mtx = np.array([[1, 2, 3],         # (3, 3)の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
                dtype = float)

In [30]:
mtx

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [31]:
# 行列のスカラー演算

mtx = np.array([[1, 2, 3],        # (3, 3)の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
                dtype = float)

In [32]:
mtx + 10       # 足し算

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]])

In [33]:
mtx - 10        # 引き算

array([[-9., -8., -7.],
       [-6., -5., -4.],
       [-3., -2., -1.]])

In [34]:
mtx*2            # 乗算

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [35]:
mtx/2            # 除算

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [36]:
# 行列の成分にアクセス

mtx = np.array([[1, 2, 3],  # (3, 3)の行列を作成
                [4, 5, 6],  # dtypeを指定しない場合は
                [7, 8, 9]]  # 成分の値に対応した型になる
              )

In [37]:
mtx.dtype       # データの型を確認

dtype('int32')

In [38]:
mtx[0]          # 1行目のすべての成分

array([1, 2, 3])

In [39]:
mtx[0,]         # 1行目のすべての成分

array([1, 2, 3])

In [40]:
mtx[0, :]       # 1行目のすべての成分

array([1, 2, 3])

In [41]:
mtx[:, 0]       # 1列目のすべての成分

array([1, 4, 7])

In [42]:
mtx[1, 1]       # 2行、2列の成分

5

In [43]:
mtx[0:2, 0:2]   # 1行～2行、1列～2列の部分行列を抽出

array([[1, 2],
       [4, 5]])

In [44]:
# 要素同士の加算、減算

a = np.array([[1, 2],   # (2. 2)の行列を作成
              [3, 4]]
            )
b = np.array([[4, 3],   # (2. 2)の行列を作成
              [2, 1]]
            )

In [45]:
a + b                   #　成分同士の足し算

array([[5, 5],
       [5, 5]])

In [46]:
a - b                   # 成分同士の引き算

array([[-3, -1],
       [ 1,  3]])

In [47]:
# 行列同士の積

a = np.array([[1, 2],  # (2. 2)の行列を作成
              [3, 4]]
            )
b = np.array([[5, 6],  # (2. 2)の行列を作成
              [7, 8]]
            )

In [48]:
np.dot(a, b)           # 行列の積を求める

array([[19, 22],
       [43, 50]])

In [49]:
# 転置行列

a = np.array([[1, 2, 3],  # 2×3の行列を作成
              [4, 5, 6]]
            )

In [50]:
np.transpose(a)           # 転置行列を求める

array([[1, 4],
       [2, 5],
       [3, 6]])